// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.21.12
// source: toolchain.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListToolchains struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId    uint64  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorktreeId   uint64  `protobuf:"varint,2,opt,name=worktree_id,json=worktreeId,proto3" json:"worktree_id,omitempty"`
	LanguageName string  `protobuf:"bytes,3,opt,name=language_name,json=languageName,proto3" json:"language_name,omitempty"`
	Path         *string `protobuf:"bytes,4,opt,name=path,proto3,oneof" json:"path,omitempty"`
}

func (x *ListToolchains) Reset() {
	*x = ListToolchains{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolchain_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListToolchains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolchains) ProtoMessage() {}

func (x *ListToolchains) ProtoReflect() protoreflect.Message {
	mi := &file_toolchain_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolchains.ProtoReflect.Descriptor instead.
func (*ListToolchains) Descriptor() ([]byte, []int) {
	return file_toolchain_proto_rawDescGZIP(), []int{0}
}

func (x *ListToolchains) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ListToolchains) GetWorktreeId() uint64 {
	if x != nil {
		return x.WorktreeId
	}
	return 0
}

func (x *ListToolchains) GetLanguageName() string {
	if x != nil {
		return x.LanguageName
	}
	return ""
}

func (x *ListToolchains) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type Toolchain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path    string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	RawJson string `protobuf:"bytes,3,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
}

func (x *Toolchain) Reset() {
	*x = Toolchain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolchain_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Toolchain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toolchain) ProtoMessage() {}

func (x *Toolchain) ProtoReflect() protoreflect.Message {
	mi := &file_toolchain_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toolchain.ProtoReflect.Descriptor instead.
func (*Toolchain) Descriptor() ([]byte, []int) {
	return file_toolchain_proto_rawDescGZIP(), []int{1}
}

func (x *Toolchain) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Toolchain) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Toolchain) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

type ToolchainGroup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StartIndex uint64 `protobuf:"varint,1,opt,name=start_index,json=startIndex,proto3" json:"start_index,omitempty"`
	Name       string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ToolchainGroup) Reset() {
	*x = ToolchainGroup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolchain_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToolchainGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolchainGroup) ProtoMessage() {}

func (x *ToolchainGroup) ProtoReflect() protoreflect.Message {
	mi := &file_toolchain_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolchainGroup.ProtoReflect.Descriptor instead.
func (*ToolchainGroup) Descriptor() ([]byte, []int) {
	return file_toolchain_proto_rawDescGZIP(), []int{2}
}

func (x *ToolchainGroup) GetStartIndex() uint64 {
	if x != nil {
		return x.StartIndex
	}
	return 0
}

func (x *ToolchainGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListToolchainsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Toolchains []*Toolchain      `protobuf:"bytes,1,rep,name=toolchains,proto3" json:"toolchains,omitempty"`
	HasValues  bool              `protobuf:"varint,2,opt,name=has_values,json=hasValues,proto3" json:"has_values,omitempty"`
	Groups     []*ToolchainGroup `protobuf:"bytes,3,rep,name=groups,proto3" json:"groups,omitempty"`
}

func (x *ListToolchainsResponse) Reset() {
	*x = ListToolchainsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolchain_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListToolchainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListToolchainsResponse) ProtoMessage() {}

func (x *ListToolchainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_toolchain_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListToolchainsResponse.ProtoReflect.Descriptor instead.
func (*ListToolchainsResponse) Descriptor() ([]byte, []int) {
	return file_toolchain_proto_rawDescGZIP(), []int{3}
}

func (x *ListToolchainsResponse) GetToolchains() []*Toolchain {
	if x != nil {
		return x.Toolchains
	}
	return nil
}

func (x *ListToolchainsResponse) GetHasValues() bool {
	if x != nil {
		return x.HasValues
	}
	return false
}

func (x *ListToolchainsResponse) GetGroups() []*ToolchainGroup {
	if x != nil {
		return x.Groups
	}
	return nil
}

type ActivateToolchain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId    uint64     `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorktreeId   uint64     `protobuf:"varint,2,opt,name=worktree_id,json=worktreeId,proto3" json:"worktree_id,omitempty"`
	Toolchain    *Toolchain `protobuf:"bytes,3,opt,name=toolchain,proto3" json:"toolchain,omitempty"`
	LanguageName string     `protobuf:"bytes,4,opt,name=language_name,json=languageName,proto3" json:"language_name,omitempty"`
	Path         *string    `protobuf:"bytes,5,opt,name=path,proto3,oneof" json:"path,omitempty"`
}

func (x *ActivateToolchain) Reset() {
	*x = ActivateToolchain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolchain_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateToolchain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateToolchain) ProtoMessage() {}

func (x *ActivateToolchain) ProtoReflect() protoreflect.Message {
	mi := &file_toolchain_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateToolchain.ProtoReflect.Descriptor instead.
func (*ActivateToolchain) Descriptor() ([]byte, []int) {
	return file_toolchain_proto_rawDescGZIP(), []int{4}
}

func (x *ActivateToolchain) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ActivateToolchain) GetWorktreeId() uint64 {
	if x != nil {
		return x.WorktreeId
	}
	return 0
}

func (x *ActivateToolchain) GetToolchain() *Toolchain {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

func (x *ActivateToolchain) GetLanguageName() string {
	if x != nil {
		return x.LanguageName
	}
	return ""
}

func (x *ActivateToolchain) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type ActiveToolchain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId    uint64  `protobuf:"varint,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	WorktreeId   uint64  `protobuf:"varint,2,opt,name=worktree_id,json=worktreeId,proto3" json:"worktree_id,omitempty"`
	LanguageName string  `protobuf:"bytes,3,opt,name=language_name,json=languageName,proto3" json:"language_name,omitempty"`
	Path         *string `protobuf:"bytes,4,opt,name=path,proto3,oneof" json:"path,omitempty"`
}

func (x *ActiveToolchain) Reset() {
	*x = ActiveToolchain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolchain_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveToolchain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveToolchain) ProtoMessage() {}

func (x *ActiveToolchain) ProtoReflect() protoreflect.Message {
	mi := &file_toolchain_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveToolchain.ProtoReflect.Descriptor instead.
func (*ActiveToolchain) Descriptor() ([]byte, []int) {
	return file_toolchain_proto_rawDescGZIP(), []int{5}
}

func (x *ActiveToolchain) GetProjectId() uint64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

func (x *ActiveToolchain) GetWorktreeId() uint64 {
	if x != nil {
		return x.WorktreeId
	}
	return 0
}

func (x *ActiveToolchain) GetLanguageName() string {
	if x != nil {
		return x.LanguageName
	}
	return ""
}

func (x *ActiveToolchain) GetPath() string {
	if x != nil && x.Path != nil {
		return *x.Path
	}
	return ""
}

type ActiveToolchainResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Toolchain *Toolchain `protobuf:"bytes,1,opt,name=toolchain,proto3,oneof" json:"toolchain,omitempty"`
}

func (x *ActiveToolchainResponse) Reset() {
	*x = ActiveToolchainResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_toolchain_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActiveToolchainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActiveToolchainResponse) ProtoMessage() {}

func (x *ActiveToolchainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_toolchain_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActiveToolchainResponse.ProtoReflect.Descriptor instead.
func (*ActiveToolchainResponse) Descriptor() ([]byte, []int) {
	return file_toolchain_proto_rawDescGZIP(), []int{6}
}

func (x *ActiveToolchainResponse) GetToolchain() *Toolchain {
	if x != nil {
		return x.Toolchain
	}
	return nil
}

var File_toolchain_proto protoreflect.FileDescriptor

var file_toolchain_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0c, 0x7a, 0x65, 0x64, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22,
	0x97, 0x01, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49,
	0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65,
	0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01,
	0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x22, 0x4e, 0x0a, 0x09, 0x54, 0x6f, 0x6f,
	0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x61, 0x77, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x61, 0x77, 0x4a, 0x73, 0x6f, 0x6e, 0x22, 0x45, 0x0a, 0x0e, 0x54, 0x6f, 0x6f,
	0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1f, 0x0a, 0x0b, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0xa6, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x0a, 0x74,
	0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x7a, 0x65, 0x64, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x54,
	0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x0a, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x68, 0x61, 0x73, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x7a, 0x65, 0x64, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x73, 0x22, 0xd1, 0x01, 0x0a, 0x11, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x49, 0x64, 0x12,
	0x35, 0x0a, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x7a, 0x65, 0x64, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x09, 0x74, 0x6f, 0x6f,
	0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c,
	0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x22, 0x98, 0x01,
	0x0a, 0x0f, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x74, 0x72, 0x65, 0x65, 0x49,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x88, 0x01, 0x01, 0x42,
	0x07, 0x0a, 0x05, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x22, 0x63, 0x0a, 0x17, 0x41, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x7a, 0x65, 0x64, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x54, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x48,
	0x00, 0x52, 0x09, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x88, 0x01, 0x01, 0x42,
	0x0c, 0x0a, 0x0a, 0x5f, 0x74, 0x6f, 0x6f, 0x6c, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x42, 0x06, 0x5a,
	0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_toolchain_proto_rawDescOnce sync.Once
	file_toolchain_proto_rawDescData = file_toolchain_proto_rawDesc
)

func file_toolchain_proto_rawDescGZIP() []byte {
	file_toolchain_proto_rawDescOnce.Do(func() {
		file_toolchain_proto_rawDescData = protoimpl.X.CompressGZIP(file_toolchain_proto_rawDescData)
	})
	return file_toolchain_proto_rawDescData
}

var file_toolchain_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_toolchain_proto_goTypes = []interface{}{
	(*ListToolchains)(nil),          // 0: zed.messages.ListToolchains
	(*Toolchain)(nil),               // 1: zed.messages.Toolchain
	(*ToolchainGroup)(nil),          // 2: zed.messages.ToolchainGroup
	(*ListToolchainsResponse)(nil),  // 3: zed.messages.ListToolchainsResponse
	(*ActivateToolchain)(nil),       // 4: zed.messages.ActivateToolchain
	(*ActiveToolchain)(nil),         // 5: zed.messages.ActiveToolchain
	(*ActiveToolchainResponse)(nil), // 6: zed.messages.ActiveToolchainResponse
}
var file_toolchain_proto_depIdxs = []int32{
	1, // 0: zed.messages.ListToolchainsResponse.toolchains:type_name -> zed.messages.Toolchain
	2, // 1: zed.messages.ListToolchainsResponse.groups:type_name -> zed.messages.ToolchainGroup
	1, // 2: zed.messages.ActivateToolchain.toolchain:type_name -> zed.messages.Toolchain
	1, // 3: zed.messages.ActiveToolchainResponse.toolchain:type_name -> zed.messages.Toolchain
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_toolchain_proto_init() }
func file_toolchain_proto_init() {
	if File_toolchain_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_toolchain_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListToolchains); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolchain_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Toolchain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolchain_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToolchainGroup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolchain_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListToolchainsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolchain_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateToolchain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolchain_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveToolchain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_toolchain_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActiveToolchainResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_toolchain_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_toolchain_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_toolchain_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_toolchain_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_toolchain_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_toolchain_proto_goTypes,
		DependencyIndexes: file_toolchain_proto_depIdxs,
		MessageInfos:      file_toolchain_proto_msgTypes,
	}.Build()
	File_toolchain_proto = out.File
	file_toolchain_proto_rawDesc = nil
	file_toolchain_proto_goTypes = nil
	file_toolchain_proto_depIdxs = nil
}
